# Generated by Django 5.1.6 on 2025-02-19 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='author',
        ),
        migrations.AddField(
            model_name='organization',
            name='authors',
            field=models.ManyToManyField(related_name='owned_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chain',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='organization.chain'),
        ),
    ]
