# Generated by Django 5.1.6 on 2025-02-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passwordchangeconfirmation'),
        ('organization', '0002_remove_organization_author_organization_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chains',
            field=models.ManyToManyField(related_name='users', to='organization.chain'),
        ),
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(related_name='users', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='restaurants',
            field=models.ManyToManyField(related_name='users', to='organization.restaurant'),
        ),
    ]
