services:
  backend:
    container_name: backend
    build:
      context: backend_iiko
    ports:
      - "8000:8000"
    volumes:
      - ./backend_iiko/backend:/backend
    env_file:
      - backend_iiko/.env

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    container_name: db
    image: postgres:14.6-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis_data:/data

  worker:
    build:
      context: backend_iiko
    container_name: celery
    hostname: worker
    entrypoint: celery
    working_dir: /backend
    command: -A backend worker --loglevel=info
    volumes:
      - ./backend_iiko/backend:/backend
    links:
      - redis
    depends_on:
      - redis
      - database
    env_file:
      - backend_iiko/.env

volumes:
  redis_data: