version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: iiko_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: iiko_redis
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: