# Generated by Django 5.1.6 on 2025-02-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
