# Generated by Django 5.1.6 on 2025-02-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_name_alter_kitchen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
