# Generated by Django 5.1.6 on 2025-03-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_product_count'),
        ('organization', '0003_alter_chain_name_alter_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ManyToManyField(related_name='categories', to='organization.restaurant'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='restaurant',
            field=models.ManyToManyField(related_name='kitchens', to='organization.restaurant'),
        ),
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ManyToManyField(related_name='products', to='organization.restaurant'),
        ),
    ]
